### ISSUE TITLE
Add documentation for each API function

### ISSUE THREAD

**Issue by IshaanDesai** [precice/julia-bindings#5]
Each API function in these bindings needs to have documentation which gives information regarding the use of the function, the input arguments and output if there is a returning entity. As an example the python bindings use `docstring` style documentation blocks for each API function, check the [initialize_data](https://github.com/precice/python-bindings/blob/36e4782b8460ba93ec6bfc307bef7bf281c540fa/cyprecice/cyprecice.pyx#L115-L136) function for the documentation block. Two tasks would be involved here:
* Finding out if there is a standard way to write documentation for Julia function and in general Julia code
* Writing documentation for all API functions

**Comment by pavelkharitenko** [comment]
@IshaanDesai can you please observe the pull request #7 ?

**Comment by erikscheurer** [comment]
At the moment, each function is documented with at least one line of code what happens if called. To correctly understand the issue, the documentation should be completed to reach a similar level like the python bindings?

Also, I don't know why the documentation is a different file, if I use the bindings I can't access the documentation I think?
```julia
julia> using PreCICE

help?> initialize
search: initialize initializeData UndefInitializer actionWriteInitialData

  No documentation found.

  PreCICE.initialize is a Function.

  # 1 method for generic function "initialize":
  [1] initialize() in PreCICE at /home/erik/.julia/packages/PreCICE/oxYbv/src/PreCICE.jl:83
```
Is there a reason for this? As far as I see the official julia packages are also documented with the documentation directly with the definition of the function.

**Comment by IshaanDesai** [comment]
Yes the documentation is expected to be similar to the one in the Python bindings. The purpose of the documentation is to give a full idea of what the particular API function does, what are the input parameters and their data types and what are the output parameters and their data types.

@erikscheurer  if you are certain that the documentation for Julia codes is in the same file then lets go with this. You can make the changes directly in https://github.com/precice/julia-bindings/pull/7
